version: 0.2
run-as: root

phases:
  install:
    commands:
      - echo "Installing app dependencies..."
      - wget https://github.com/zaproxy/zaproxy/releases/download/v2.14.0/ZAP_2.14.0_Linux.tar.gz
      - tar -xvf ZAP_2.14.0_Linux.tar.gz

  build:
    commands:
      - echo "Retrieving Load Balancer DNS name..."
      # Extract Target Group ARN from ECS Service
      - TARGET_GROUP_ARN="$(aws ecs describe-services --cluster demo --services ecs-demo-service --query 'services[0].loadBalancers[0].targetGroupArn' --output text)"
      # Describe Target Group to get Load Balancer ARN
      - LOAD_BALANCER_ARN="$(aws elbv2 describe-target-groups --target-group-arns $TARGET_GROUP_ARN --query 'TargetGroups[0].LoadBalancerArns[0]' --output text)"
      # Describe Load Balancer to get DNS Name
      - LOAD_BALANCER_DNS="$(aws elbv2 describe-load-balancers --load-balancer-arns $LOAD_BALANCER_ARN --query 'LoadBalancers[0].DNSName' --output text)"
      - echo "Load Balancer DNS Name = $LOAD_BALANCER_DNS"
      # - echo "Load Balancer DNS: $LOAD_BALANCER_DNS"
      - ./ZAP_2.14.0/zap.sh -cmd -quickurl "http://$LOAD_BALANCER_DNS" -quickprogress -quickout ../zap_report.html

  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files: 
    - zap_report.html